### ISSUE TITLE
Kernel question

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#18]
When implementing our original BAC/ESMACS scripts, I used the NAMD kernel, and implemented kernels for tar etc. 

However, I note in the reimplementation: 

https://github.com/radical-collaboration/GB-SC18/blob/14421782554babd55d7ce0b49854d7fa813da949/scripts/esmacs/bac_runner_entk_0-6.py#L60

You simply launch NAMD via bash. Can you explain why this is? Surely it breaks the portability of the application? 

thanks. 

Stefan

**Comment by jdakka** [comment]
This is specific to Blue Waters, there is no "module load namd" 
these are the instructions from BW: https://bluewaters.ncsa.illinois.edu/namd

Also in the latest EnTK the "MD plugins" are no longer accessible.

**Comment by sjzasada** [comment]
But why not then implement a NAMD kernel that executes the NAMD binary without doing module load? 

Sorry - I'm just trying to understand how the process works 😃

**Comment by jdakka** [comment]
@vivek-bala can you explain why the decision to remove the MD plugins

**Comment by vivek-bala** [comment]
Hey Stefan!

The idea initially behind having kernel plugins was to be able to share the kernel definitions across the various projects. These kernel definitions (as you already know) allowed the users to define resource specific attributes (such as modules to be loaded, executable, arguments) for multiple resources in one location. It was quite useful to have it in such mode. 

Different projects required making minor changes to these kernel plugins which meant to dig into these kernel plugins (inside the package at src/radical/entk/kernel_plugins/ and reinstall) for each of them, this felt a bit redundant. It also became difficult to maintain up-to-date (with changes on the HPCs) as the number of these application kernels increased. Thinking about it, the kernel plugin was really a dictionary with resource label as the key and the executable, pre_exec (to load necessary environment before executable), arguments and post_exec (some processing after the executable) which can be created rather easily by the user itself rather than enforcing a kernel plugin **format** and file. With that in mind, in the current version of EnTK, we decided to remove the kernel plugin format/file and let the user directly specify those attributes as part of each Task. 

The user is now free to create his/her scripts specific to a resource or to multiple resources. The user can do something like the following:

```
kernel_defs = { 'ncsa.bw': { 'executable': [], 'pre_exec': [], 'arguments': []},
                         'ornl.titan': { 'executable': [], 'pre_exec': [], 'arguments': []},
                         'epsrc.archer': { 'executable': [], 'pre_exec': [], 'arguments': []}

task = Task()
task.pre_exec = kernel_defs[resource_label]['pre_exec']
task.executable = kernel_defs[resource_label]['executable']
task.arguments = kernel_defs[resource_label]['arguments']
```

If we take out all the complexity and the format, this was what the kernel plugin was essentially doing. Hence, the decision to remove it. 

That ended up being a long description, hopefully that helps!

**Comment by sjzasada** [comment]
From a user point of view, I found it useful to be able to take advantage of pre-defined kernels to run NAMD without myself having to find where NAMD is on each machine and how to run it. I'd suggest considering adding this feature back in some way.
